import groupPalette from '../themes/group/palette.css?raw';
import schoolPalette from '../themes/school/palette.css?raw';
import workPalette from '../themes/work/palette.css?raw';
import docsPalette from '../themes/docs/palette.css?raw';
import { themes, type ThemeId } from '../themes/index.js';

/**
 * Runtime brand switching for the documentation site.
 *
 * A product ships exactly one theme: its entry point pairs the contract with one palette, and the
 * palette writes the semantic roles onto `:root`. That is correct for an application and useless
 * for documentation — a single document can only hold one `:root`, so Storybook could only ever
 * show one brand, which is why it appeared to be the School design system.
 *
 * The fix is to re-scope rather than to re-author. Each palette is read as text from the *real*
 * `themes/<id>/palette.css` and its two selectors are rewritten from `:root` / `.dark` to
 * `[data-brand="<id>"]` / `[data-brand="<id>"].dark`. All four then coexist in one document and
 * the toolbar picks between them by setting one attribute.
 *
 * Two properties matter, and both come from doing it this way:
 *
 * - **No duplicated colour data.** The palettes are the source; nothing here restates a hex, so a
 *   palette edit reaches the docs with no second copy to update.
 * - **Nothing ships.** This lives in `.storybook/`, runs only in the docs site, and changes no
 *   component, no token and no theme entry point. Products keep importing one theme exactly as
 *   they did.
 *
 * It works at all because the contract in `themes/base/base.css` binds Tailwind's `--color-*`
 * namespace to the semantic vars with `@theme inline`, i.e. as live `var()` references resolved
 * from the cascade on every paint — so moving the values to a different selector is enough to
 * re-theme every component, with no rebuild and no component aware that a brand exists.
 */

export const BRAND_IDS = ['group', 'school', 'work', 'docs'] as const satisfies readonly ThemeId[];
export type BrandId = (typeof BRAND_IDS)[number];

/** The default brand for a freshly opened story — the group-level corporate identity. */
export const DEFAULT_BRAND: BrandId = 'group';

const PALETTES: Record<BrandId, string> = {
  group: groupPalette,
  school: schoolPalette,
  work: workPalette,
  docs: docsPalette,
};

/**
 * Rewrite a palette's two top-level selectors into a brand scope.
 *
 * Deliberately strict: every palette is generated by `scripts/generate-palettes.mjs` and has
 * exactly one `:root` block and one `.dark` block. If that ever stops being true the throw is
 * what surfaces it, rather than a brand silently rendering with half a palette.
 */
function scopeToBrand(css: string, id: BrandId): string {
  const light = `[data-brand='${id}']`;
  // Two dark selectors, because a brand is applied in two places: the toolbar sets `data-brand`
  // on <html> alongside `.dark` (same element), while a theme page pins a brand on a nested
  // container *inside* the dark root (ancestor). Matching only the first would leave the pinned
  // brand pages stuck in light values whenever the scheme is dark.
  const dark = `${light}.dark, .dark ${light}`;

  const scoped = css.replace(/^:root\s*\{/m, `${light} {`).replace(/^\.dark\s*\{/m, `${dark} {`);

  if (!scoped.includes(`${light} {`) || !scoped.includes(`${dark} {`)) {
    throw new Error(
      `brand-themes: ${id}/palette.css no longer has the expected ":root" and ".dark" blocks, ` +
        'so it cannot be scoped for the brand switcher.',
    );
  }
  return scoped;
}

const STYLE_ID = 'axa-brand-themes';

/**
 * Install all four scoped palettes into the document, once.
 *
 * Called at module scope from `preview.tsx` so the styles are present before the first story
 * paints — a brand applied in an effect would show one frame of unthemed colour on every load.
 */
export function installBrandThemes(): void {
  if (typeof document === 'undefined' || document.getElementById(STYLE_ID)) return;

  const style = document.createElement('style');
  style.id = STYLE_ID;
  style.textContent = BRAND_IDS.map((id) => scopeToBrand(PALETTES[id], id)).join('\n');
  document.head.append(style);
}

/** Apply a brand by setting the one attribute the scoped palettes key off. */
export function applyBrand(id: BrandId): void {
  if (typeof document === 'undefined') return;
  document.documentElement.dataset.brand = id;
}

/** Toolbar entries, named from the theme registry so the labels cannot drift from the package. */
export const BRAND_ITEMS = BRAND_IDS.map((id) => ({
  value: id,
  title: `Munaxa ${themes[id].name}`,
}));
