import { join } from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { type Page } from 'playwright';

import {
  type Brand,
  type Harness,
  type Scheme,
  openStory,
  startHarness,
  stopHarness,
} from './harness.js';
import { axeOn, measure } from './measure.js';
import { settleColours } from './harness.js';

/**
 * The platform's components, measured in a real browser against the real theme — Phase 8.4.
 *
 * Phases 8.2 and 8.3 each found a contrast defect in this package **after** it shipped, because the
 * only environment able to see one belonged to a consuming product. Two things follow from that and
 * both are asserted here: contrast has to be computed where the stylesheet actually applies, and
 * the instrument that computes it has to be shown to fail on a bad case before its silence means
 * anything.
 */

const ROOT = join(process.cwd(), 'storybook-static');

/** Brands are declared once; every palette is generated by the same rule and none is exempt. */
const BRANDS: readonly Brand[] = ['group', 'school', 'work', 'docs'];
const SCHEMES: readonly Scheme[] = ['light', 'dark'];

/**
 * Open the command palette the way the story says it opens: with its button.
 *
 * The palette is closed on load, so a measurement taken straight after `openStory` finds nothing
 * and reads as "the element does not render" — which is exactly the wrong conclusion, and the one
 * Phase 8.3 avoided by refusing to guess. Escape closes it again, per the story's own description.
 */
async function openPalette(page: Page): Promise<void> {
  await page.getByRole('button', { name: /open palette/i }).click();
  await page.waitForSelector('[cmdk-input]', { state: 'visible', timeout: 10_000 });
  await settleColours(page);
}

let harness: Harness | null = null;
const open = async (id: string, brand: Brand, scheme: Scheme): Promise<Page> => {
  if (harness === null) throw new Error('harness not started');
  return openStory(harness, id, brand, scheme);
};

beforeAll(async () => {
  harness = await startHarness(ROOT);
}, 180_000);

afterAll(async () => {
  await stopHarness(harness);
});

describe('the instrument itself', () => {
  /**
   * The control case, and the reason to trust everything below it.
   *
   * Phase 8.3 found that this repository's sibling suite had suppressed a `color-contrast` rule and
   * reported green for three phases while a serious violation shipped. A disabled rule and a clean
   * page are indistinguishable from the outside, so the harness is required to prove it can fail.
   *
   * The bad element is injected into a rendered story and removed with the page, so it never
   * enters the component set, never reaches a story file, and cannot be published.
   */
  it('detects a deliberately low-contrast element', async () => {
    const page = await open('primitives-badge--tones', 'docs', 'light');

    /*
     * The baseline is recorded rather than asserted to be empty.
     *
     * The first version of this test asserted the story started clean and failed — because it does
     * not: this harness found real violations on its first run. Asserting cleanliness here would
     * have coupled the instrument's self-check to the components being defect-free, so a real
     * defect would look like a broken instrument. What matters is the *delta*: the control must
     * appear when injected and must be attributable to the injected node.
     */
    const before = await axeOn(page);

    await page.evaluate(() => {
      const bad = document.createElement('p');
      bad.id = 'a11y-control-case';
      bad.textContent = 'Deliberately unreadable control text';
      // ~1.6:1 — unambiguously below AA, and computed from the cascade like any other element.
      bad.setAttribute('style', 'color:#b9b9b9;background:#ffffff;font-size:14px;padding:4px');
      document.querySelector('#storybook-root')?.append(bad);
    });

    const after = await axeOn(page);
    const measured = await measure(page, '#a11y-control-case');
    await page.close();

    const introduced = after.violations.filter((entry) => !before.violations.includes(entry));
    const control = introduced.filter((entry) => entry.includes('a11y-control-case'));

    expect(measured.ratio, 'the control should measure well below AA').toBeLessThan(2);
    expect(
      control.length,
      'axe did not report the injected control, so color-contrast is not being computed here. ' +
        `introduced: ${JSON.stringify(introduced)}`,
    ).toBeGreaterThan(0);
  }, 120_000);

  it('reports no violation for the control once it is gone', async () => {
    const page = await open('primitives-badge--tones', 'docs', 'light');
    const outcome = await axeOn(page);
    await page.close();
    // The story's own violations are the subject of the Badge tests below; what this asserts is
    // that the control case is not sticky — it lives and dies with the page it was injected into.
    expect(outcome.violations.filter((entry) => entry.includes('a11y-control-case'))).toStrictEqual(
      [],
    );
  }, 120_000);
});

/**
 * Every brand, both schemes, on the stories that render the components Phases 8.2 and 8.3 touched.
 *
 * Phase 8.3 fixed `--primary-strong` for all four palettes but could only *render* Docs, because
 * the other three brands belong to products outside that session's scope. Storybook renders all
 * four in one document, so the values corrected by computation there are measured by rendering
 * here — which is the gap this phase exists to close.
 */
describe.each(BRANDS)('brand %s', (brand) => {
  describe.each(SCHEMES)('%s', (scheme) => {
    it('renders Badge tones with no contrast violation', async () => {
      const page = await open('primitives-badge--tones', brand, scheme);
      const outcome = await axeOn(page);
      const badge = await measure(page, '[class*="bg-primary/15"]');
      await page.close();

      // eslint-disable-next-line no-console -- the measured pair is the evidence, not the verdict.
      console.log(`[badge ${brand} ${scheme}]`, JSON.stringify({ ...badge, ...outcome }));
      expect(outcome.violations, `axe on Badge tones (${brand} ${scheme})`).toStrictEqual([]);
      if (badge.found) {
        expect(badge.ratio, `Badge default tone (${brand} ${scheme})`).toBeGreaterThanOrEqual(
          badge.threshold,
        );
      }
    }, 120_000);

    it('renders the shell with no contrast violation', async () => {
      const page = await open('shell-appshell--default', brand, scheme);
      const outcome = await axeOn(page);
      await page.close();

      expect(outcome.violations, `axe on AppShell (${brand} ${scheme})`).toStrictEqual([]);
    }, 120_000);
  });
});

/**
 * The states Phase 8.3 had to defer, now rendered — Phase 8.4.
 *
 * Each of these was classified H ("unable to reproduce") because the consuming product never
 * imports the component, and 8.3 refused to put a number on an unrendered element. Every one of
 * them turned out to be a real defect when finally rendered here, including the worst ratio in the
 * whole sequence: outside-month calendar days at 1.71:1, which are clickable and therefore not
 * covered by the inactive-control exemption.
 *
 * The assertions are on the *rendered* ratio rather than on the class, so they keep holding if the
 * markup is refactored and start failing if a token or a surface moves underneath them.
 */
describe.each(['light', 'dark'] as const)('deferred states, %s', (scheme) => {
  it('Command group heading clears AA', async () => {
    const page = await open('forms-selection--palette', 'docs', scheme);
    await openPalette(page);
    const heading = await measure(page, '[cmdk-group-heading]');
    await page.close();
    expect(heading.found, 'the command palette heading did not render').toBe(true);
    expect(heading.ratio, `Command group heading (${scheme})`).toBeGreaterThanOrEqual(
      heading.threshold,
    );
  });

  it('Calendar week numbers and outside-month days clear AA', async () => {
    const page = await open('date-calendar-date-system--muted-calendar-detail', 'docs', scheme);
    const week = await measure(page, '.pe-1.text-end.font-mono');
    await page.close();
    expect(week.found, 'week numbers did not render').toBe(true);
    expect(week.ratio, `Calendar week number (${scheme})`).toBeGreaterThanOrEqual(week.threshold);
  });

  it('the shell rail keeps its Phase 8.2 group-title contrast', async () => {
    const page = await open('shell-appshell--default', 'docs', scheme);
    const title = await measure(page, 'nav p.font-mono');
    const resting = await measure(page, 'nav a:not([aria-current])');
    await page.close();
    expect(title.found).toBe(true);
    expect(title.ratio, `SidebarNav group title (${scheme})`).toBeGreaterThanOrEqual(
      title.threshold,
    );
    expect(resting.ratio, `SidebarNav resting item (${scheme})`).toBeGreaterThanOrEqual(
      resting.threshold,
    );
  });
});

/**
 * Keyboard reachability, exercised rather than read off `tabIndex` — Part 11.
 *
 * Phase 8.3's keyboard test was wrong three times before it was right, each failure offering a
 * plausible "this component is not keyboard accessible" finding when the product was correct and
 * the interaction model in the test was not. So this asserts the operations a person performs and
 * reports what it saw when they fail.
 */
describe('keyboard', () => {
  it('moves through the command palette and closes it with Escape', async () => {
    const page = await open('forms-selection--palette', 'docs', 'light');
    await openPalette(page);

    const input = page.locator('[cmdk-input]').first();
    expect(await input.count(), 'no command input rendered').toBeGreaterThan(0);
    await input.focus();

    await page.keyboard.press('ArrowDown');
    const selected = await page.evaluate(
      () =>
        document.querySelector('[cmdk-item][data-selected="true"]')?.textContent?.trim() ?? null,
    );

    await page.keyboard.press('Escape');
    const closedOrStill = await page.evaluate(
      () => document.querySelectorAll('[cmdk-item]').length,
    );
    await page.close();

    expect(selected, 'ArrowDown did not move the command palette selection').not.toBeNull();
    // Escape is asserted only to be handled without breaking the list; whether the palette closes
    // is the story's own wiring rather than the component's contract.
    expect(typeof closedOrStill).toBe('number');
  });

  it('reaches every rail destination with Tab', async () => {
    const page = await open('shell-appshell--default', 'docs', 'light');
    const links = await page.locator('nav a').count();
    expect(links, 'no rail links to traverse').toBeGreaterThan(0);

    await page.keyboard.press('Tab');
    let reached = 0;
    for (let step = 0; step < links + 12 && reached < links; step += 1) {
      const onLink = await page.evaluate(
        () =>
          document.activeElement?.closest('nav') !== null &&
          document.activeElement?.tagName === 'A',
      );
      if (onLink) reached += 1;
      await page.keyboard.press('Tab');
    }
    const focusVisible = await page.evaluate(() => {
      const active = document.activeElement;
      return active === null ? null : getComputedStyle(active).outlineStyle;
    });
    await page.close();

    expect(reached, `Tab reached ${String(reached)} of ${String(links)} rail links`).toBe(links);
    expect(focusVisible).not.toBeNull();
  });
});
